ahrs_config:
  print_flag: true
  calibration_times: 1000
  filter_order: 2
  acc_filter_cutoff: 50
  vel_filter_cutoff: 0.1
  pos_filter_cutoff: 0.1
  file_path: "/home/yzc/project/robotswitch/src/robotswitch_controller/test/ahrs_dyn_hpf.txt"
